(async function () {
  var BUILDER_URL = 'https://architect-henna-eta.vercel.app/api/builder';
  var SECRET = 'ambrosia-build-2026';
  var BOT_TOKEN = 'YOUR_BOT_TOKEN_HERE';
  var APP_ID = '1539701435237662830';
  var PUB_KEY = 'b9f4224b6bcc697b8d910f4095fb586c987552a63c2b53b945880f0ec5c29454';

  var GUILD_ID = prompt('Enter Server ID (mandatory):', '1539404742055166045');
  if (!GUILD_ID || GUILD_ID.trim() === '') {
    console.error('[Ambrosia Builder] No Server ID. Aborted.');
    return;
  }
  GUILD_ID = GUILD_ID.trim();

  console.log('[Ambrosia Builder] Building: ' + GUILD_ID);

  try {
    var res = await fetch(BUILDER_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ secret: SECRET, guild_id: GUILD_ID })
    });

    var data = await res.json();
    if (!res.ok) {
      console.error('[Ambrosia Builder] Failed:', data.error);
      return;
    }

    console.log('[Ambrosia Builder] Done in ' + data.time);

    console.log('\n===== ROLES =====');
    var roleEntries = Object.entries(data.roles);
    for (var i = 0; i < roleEntries.length; i++) {
      console.log('  ' + roleEntries[i][0] + ': ' + roleEntries[i][1]);
    }

    console.log('\n===== CATEGORIES =====');
    var catEntries = Object.entries(data.categories);
    for (var i = 0; i < catEntries.length; i++) {
      console.log('  ' + catEntries[i][0] + ': ' + catEntries[i][1]);
    }

    console.log('\n===== CHANNELS =====');
    var chEntries = Object.entries(data.channels);
    var catNames = Object.keys(data.categories);
    for (var i = 0; i < chEntries.length; i++) {
      if (catNames.indexOf(chEntries[i][0]) === -1) {
        console.log('  ' + chEntries[i][0] + ': ' + chEntries[i][1]);
      }
    }

    var r = data.roles;
    var c = data.channels;

    var cat = data.categories;

    var envLines = [
      '# ============================================',
      '# AMBROSIA MAIN BOT - ENVIRONMENT VARIABLES',
      '# Generated by Ambrosia Architect',
      '# ============================================',
      '',
      '# --- Discord Bot Credentials ---',
      'DISCORD_APPLICATION_ID=' + APP_ID,
      'DISCORD_APPLICATION_PUBLIC_KEY=' + PUB_KEY,
      'DISCORD_BOT_TOKEN=' + BOT_TOKEN,
      'DISCORD_GUILD_ID=' + GUILD_ID,
      '',
      '# --- Role IDs ---',
      'DISCORD_OWNER_ROLE_ID=' + (r['Owner'] || ''),
      'DISCORD_SELLER_ROLE_ID=' + (r['Seller'] || ''),
      'DISCORD_STAFF_ROLE_ID=' + (r['Staff'] || ''),
      'DISCORD_CUSTOMER_ROLE_ID=' + (r['Verified Customer'] || ''),
      'DISCORD_MEMBER_ROLE_ID=' + (r['Member'] || ''),
      '',
      '# --- Category IDs ---',
      'DISCORD_TICKETS_CATEGORY_ID=' + (cat['support'] || ''),
      '',
      '# --- Channel IDs ---',
      'DISCORD_RULES_CHANNEL_ID=' + (c['rules'] || ''),
      'DISCORD_ANNOUNCEMENTS_CHANNEL_ID=' + (c['announcements'] || ''),
      'DISCORD_PRODUCT_CATALOG_CHANNEL_ID=' + (c['product catalog'] || ''),
      'DISCORD_LINKS_CHANNEL_ID=' + (c['links'] || ''),
      'DISCORD_GENERAL_CHAT_CHANNEL_ID=' + (c['general chat'] || ''),
      'DISCORD_OFF_TOPIC_CHANNEL_ID=' + (c['off topic'] || ''),
      'DISCORD_VERIFIED_CHAT_CHANNEL_ID=' + (c['verified chat'] || ''),
      'DISCORD_VERIFIED_VOICE_CHANNEL_ID=' + (c['verified voice'] || ''),
      'DISCORD_TICKET_PANEL_CHANNEL_ID=' + (c['open your ticket'] || ''),
      'DISCORD_TICKET_LOG_CHANNEL_ID=' + (c['ticket logs'] || ''),
      'DISCORD_STAFF_CHAT_CHANNEL_ID=' + (c['staff chat'] || ''),
      'DISCORD_ORDER_NOTIFICATION_CHANNEL_ID=' + (c['order notifications'] || ''),
      'DISCORD_XMR_ADDRESSES_CHANNEL_ID=' + (c['xmr addresses'] || ''),
      'DISCORD_GENERAL_VOICE_CHANNEL_ID=' + (c['general voice'] || ''),
      'DISCORD_SUPPORT_VOICE_CHANNEL_ID=' + (c['support voice'] || ''),
      '',
      '# --- Secrets ---',
      'PANEL_SECRET=ambrosia-send-panel-2026',
      'SETUP_SECRET=ambrosia-setup-2026',
      'UPDATE_LINKS_SECRET=ambrosia-update-links-2026',
      'UPDATE_PRICING_SECRET=ambrosia-update-pricing-2026',
      'SEND_MESSAGES_SECRET=ambrosia-send-messages-2026',
      '',
      '# --- Constants ---',
      'XMR_RATE_USD=168.51',
      'TICKET_SERVER_INVITE=https://discord.gg/V5hcFpehb5',
      'PRODUCT_SERVER_INVITE=https://discord.gg/bT9dpnerP4',
      'SELLER_WEBSITE=https://ambrosiaovh.vercel.app',
      'OFFICIAL_WEBSITE=https://ambrosia.ovh'
    ];

    console.log('\n===== .env FILE =====');
    console.log(envLines.join('\n'));

    try {
      await navigator.clipboard.writeText(envLines.join('\n'));
      console.log('[Ambrosia Builder] .env copied to clipboard!');
    } catch (e) {
      console.log('[Ambrosia Builder] Copy .env manually from above.');
    }

    console.log('\n[Ambrosia Builder] COMPLETE.');

  } catch (err) {
    console.error('[Ambrosia Builder] Error:', err.message);
  }
})();
